// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactInfo = { email: string | null, phone: string | null, fax: string | null, social_media: { [key: string]: string }, };
