// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedEntity } from "./ExtractedEntity";

export type EntityExtractionResult = { url: string, objective: string, entities: Array<ExtractedEntity>, raw_analysis: string, extraction_confidence: number, };
