// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStatus } from "./EventStatus";
import type { Location } from "./Location";
import type { Person } from "./Person";
import type { Price } from "./Price";

export type Event = { title: string, description: string | null, start_date: string | null, end_date: string | null, start_time: string | null, end_time: string | null, location: Location | null, organizer: Person | null, attendees: Array<Person>, category: string | null, tags: Array<string>, price: Price | null, registration_url: string | null, status: EventStatus, };
