// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { JobListing } from "./JobListing";
import type { Location } from "./Location";
import type { NewsArticle } from "./NewsArticle";
import type { Organization } from "./Organization";
import type { Person } from "./Person";
import type { Product } from "./Product";

export type ExtractedEntity = { "type": "Person" } & Person | { "type": "Location" } & Location | { "type": "Event" } & Event | { "type": "Product" } & Product | { "type": "Organization" } & Organization | { "type": "NewsArticle" } & NewsArticle | { "type": "JobListing" } & JobListing;
