// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmploymentType } from "./EmploymentType";
import type { Location } from "./Location";
import type { Organization } from "./Organization";
import type { SalaryRange } from "./SalaryRange";

export type JobListing = { title: string, company: Organization | null, location: Location | null, description: string | null, requirements: Array<string>, salary_range: SalaryRange | null, employment_type: EmploymentType, remote_allowed: boolean, posted_date: string | null, application_deadline: string | null, application_url: string | null, };
