// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractedEntity } from "./ExtractedEntity";

export type LLMResponse = { is_objective_met: boolean, results: Array<ExtractedEntity> | null, analysis: string | null, };
