// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Location = { name: string | null, address: string | null, city: string | null, state: string | null, country: string | null, postal_code: string | null, latitude: number | null, longitude: number | null, venue_type: string | null, };
