// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export type NewsArticle = { headline: string, summary: string | null, content: string | null, author: Person | null, publication_date: string | null, source: string | null, category: string | null, tags: Array<string>, url: string | null, };
