// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactInfo } from "./ContactInfo";
import type { Location } from "./Location";
import type { Person } from "./Person";

export type Organization = { name: string, description: string | null, website: string | null, industry: string | null, size: string | null, founded: string | null, headquarters: Location | null, employees: Array<Person>, contact_info: ContactInfo, };
