// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Person = { first_name: string | null, last_name: string | null, full_name: string | null, title: string | null, company: string | null, email: string | null, phone: string | null, bio: string | null, social_links: Array<string>, };
