// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Price } from "./Price";
import type { ProductAvailability } from "./ProductAvailability";
import type { Review } from "./Review";

export type Product = { name: string, description: string | null, price: Price | null, brand: string | null, category: string | null, sku: string | null, availability: ProductAvailability, specifications: { [key: string]: string }, images: Array<string>, reviews: Array<Review>, rating: number | null, };
