// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export type Review = { author: Person | null, rating: number, title: string | null, content: string | null, date: string | null, verified_purchase: boolean, };
