// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SalaryPeriod } from "./SalaryPeriod";

export type SalaryRange = { min: number | null, max: number | null, currency: string, period: SalaryPeriod, };
